apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: confluence
  name: confluence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
    spec:
      volumes:
        - name: confluence-data
          hostPath:
            path: /media/virtual/confluence-data
      containers:
        - image: atlassian/confluence-server:6.6.15
          name: confluence
          ports:
            - name: tomcat
              containerPort: 8090
          volumeMounts:
            - name: confluence-data
              mountPath: /var/atlassian/application-data/confluence
          env:
            - name: ATL_JDBC_USER
              valueFrom:
                secretKeyRef:
                  name: confluence-db-credentials
                  key: user
            - name: ATL_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: confluence-db-credentials
                  key: pass
            - name: ATL_DB_TYPE
              value: postgresql
            - name: ATL_JDBC_URL
              value: jdbc:postgresql://postgres/confluence
            - name: ATL_PROXY_NAME
              value: confluence.dotslashme.com
            - name: ATL_PROXY_PORT
              value: "443"
            - name: ATL_TOMCAT_SCHEME
              value: https