kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-data
          hostPath:
            path: /media/virtual/nextcloud-data
      containers:
        - name: nextcloud
          image: nextcloud:18-apache
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
          env:
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-credentials
                  key: pass
            - name: POSTGRES_HOST
              value: postgres
            - name: REDIS_HOST
              value: redis
            - name: TRUSTED_PROXIES
              value: 192.168.0.0/16
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.dotslashme.com
            - name: NEXTCLOUD_TABLE_PREFIX
              value: ""
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-credentials
                  key: user
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-credentials
                  key: pass
