apiVersion: v1
kind: ConfigMap
metadata:
  name: sysctl-configmap
  labels:
    app: smb-server
data:
  sysctl-config: |
    net.inet.tcp.sendspace=262144
    net.inet.tcp.recvspace=262144
    net.inet.tcp.delayed_ack=0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smb-server
  name: smb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-server
  template:
    metadata:
      labels:
        app: smb-server
    spec:
      volumes:
        - name: media
          hostPath:
            path: /media/nfs/media
        - name: sysctl-configmap-volume
          configMap:
            name: sysctl-configmap
            items:
              - key: sysctl-config
                path: sysctl.conf
      containers:
        - image: dperson/samba
          imagePullPolicy: Always
          name: smb-server
          ports:
            - name: netbios
              containerPort: 139
            - name: smb
              containerPort: 445
          env:
            - name: SHARE
              value: "movies;/media/movies"
            - name: SHARE2
              value: "music;/media/music"
            - name: SHARE3
              value: "series;/media/series"
            - name: SHARE4
              value: "download;/media/download"
            - name: SMB
              value: "true"
          volumeMounts:
            - name: media
              mountPath: /media
            - name: sysctl-configmap-volume
              mountPath: /etc/sysctl.conf
              subPath: sysctl.conf

