#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$CONFLUENCE_USER" WITH PASSWORD '$CONFLUENCE_PASS';
    CREATE DATABASE "$CONFLUENCE_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$CONFLUENCE_USER" TO "$CONFLUENCE_USER";
EOSQL