#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$NEXTCLOUD_USER" WITH PASSWORD '$NEXTCLOUD_PASS';
    CREATE DATABASE "$NEXTCLOUD_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$NEXTCLOUD_USER" TO "$NEXTCLOUD_USER";
EOSQL